### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by 177715031** [BrenoCPimenta/PokerAI#2]
请问大佬，训练效果怎么样，这个模型的1vs1的吗？我在ACPC获得的数据和你的类似，如何做到数据转化呢？

**Comment by BrenoCPimenta** [comment]
Simple translation performed by google:
实际上，该模型是1vs5。
该模型使用递归神经网络，与更多最新解决方案相比，结果并不十分令人满意。使用标准规范来提供模型，没有创新之处，该文件中的部分内容位于：https://github.com/BrenoCPimenta/PokerAI/blob/master/pokerRNN/data/conversion/normalize_data.py
如果您还有其他具体问题，可以再次询问

Actually the model is 1vs5.
The model uses a recurrent neural network and the results were not very satisfactory compared to compared to more recent solutions. Standard data normalization techniques were used into the data who feeds the model, nothing innovative, part of which are in this file: https://github.com/BrenoCPimenta/PokerAI/blob/master/pokerRNN/data/conversion/normalize_data.py
If you have any more specific questions, do not hesitate to ask!
